name: Puppy-RTOS Targets build check

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # Runs at 16:00 UTC (BeiJing 00:00) on the 1st of every month
  schedule:
    - cron:  '0 16 1 * *'
  push:
    paths-ignore:
      - docs/**
      - '**/README.md'
  pull_request:
    paths-ignore:
      - docs/**
      - '**/README.md'

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:
    runs-on: ubuntu-latest
    name: ${{ matrix.legs.Targets }}
    strategy:
      fail-fast: false
      matrix:
       legs:
         -  Targets: "stm32-f407-fkm1"
         -  Targets: "stm32-f412-nucleo"
         -  Targets: "raspberry-pico"

    steps:
      - uses: actions/checkout@v3
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Install Arm ToolChains
        if: ${{ success() }}
        shell: bash
        run: |
          wget -q https://github.com/RT-Thread/toolchains-ci/releases/download/v1.3/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2
          sudo tar xjf gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2 -C /opt
          /opt/gcc-arm-none-eabi-10-2020-q4-major/bin/arm-none-eabi-gcc --version

      - name: Xmake Build
        if: ${{ success() }}
        shell: bash
        env:
          Targets: ${{ matrix.legs.Targets }}
        run: |
          xmake --version
          xmake f -p cross --sdk=/opt/gcc-arm-none-eabi-10-2020-q4-major --build_target=$Targets
          xmake
