name: Puppy-RTOS Boards build check

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # Runs at 16:00 UTC (BeiJing 00:00) on the 1st of every month
  schedule:
    - cron:  '0 16 1 * *'
  push:
    paths-ignore:
      - docs/**
      - '**/README.md'
  pull_request:
    paths-ignore:
      - docs/**
      - '**/README.md'

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:
    runs-on: ubuntu-latest
    name: ${{ matrix.legs.Boards }}
    strategy:
      fail-fast: false
      matrix:
       legs:
         - {Boards: "stm32-f407-fkm1",   ARCH: "arm"}
         - {Boards: "stm32-f412-nucleo", ARCH: "arm"}
         - {Boards: "raspberry-pico",    ARCH: "arm"}
         - {Boards: "qemu-virt-riscv",   ARCH: "riscv"}

    env:
      Boards: ${{ matrix.legs.Boards }}
    steps:
      - uses: actions/checkout@v3
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Install Arm ToolChains
        if: ${{ success() && matrix.legs.ARCH == 'arm'}}
        shell: bash
        run: |
          wget -q https://github.com/RT-Thread/toolchains-ci/releases/download/v1.3/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2
          sudo tar xjf gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2 -C /opt
          /opt/gcc-arm-none-eabi-10-2020-q4-major/bin/arm-none-eabi-gcc --version
          xmake --version
          xmake f -p cross --sdk=/opt/gcc-arm-none-eabi-10-2020-q4-major --build_board=$Boards

      - name: Install RISC-V ToolChains
        if: ${{ success() && matrix.legs.ARCH == 'riscv'}}
        shell: bash
        run: |
          wget -q https://github.com/RT-Thread/toolchains-ci/releases/download/v1.4/riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14.tar.gz
          sudo tar zxf riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14.tar.gz -C /opt
          /opt/riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14/bin/riscv64-unknown-elf-gcc --version
          xmake --version
          xmake f -p cross --sdk=/opt/riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14 --build_board=$Boards

      - name: Xmake Build
        if: ${{ success() }}
        shell: bash
        run: |
          xmake
