name: AutoTestCI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # Runs at 16:00 UTC (BeiJing 00:00) on the 1st of every month
  schedule:
    - cron:  '0 16 1 * *'
  push:
    paths-ignore:
      - documentation/**
      - '**/README.md'
      - '**/README_zh.md'
  pull_request:
    paths-ignore:
      - documentation/**
      - '**/README.md'
      - '**/README_zh.md'

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  test:
    runs-on: ubuntu-latest
    name: AutoTestCI
    strategy:
      fail-fast: false
    env:
      TEST_QEMU_ARCH: "riscv32"
      TEST_QEMU_MACHINE: "virt"
      TEST_BOARD: "qemu-virt-riscv"
    steps:
    - uses: actions/checkout@v3
    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest

    - name: Install Tools
      if: ${{ success() }}
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get -yqq install qemu-system git

    - name: Install RISC-V ToolChains
      if: ${{ success() }}
      run: |
        wget -q https://github.com/RT-Thread/toolchains-ci/releases/download/v1.4/riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14.tar.gz
        sudo tar zxf riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14.tar.gz -C /opt
        /opt/riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14/bin/riscv64-unknown-elf-gcc --version
        xmake --version
        xmake f -p cross --sdk=/opt/riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14 --build_board=$TEST_BOARD -m debug

    - name: Build
      if: ${{ success() }}
      shell: bash
      run: |
        xmake

    - name: Start run Test
      if: ${{success() }}
      run: |
        git clone https://github.com/Guozhanxin/UtestRunner.git
        pushd UtestRunner
        git checkout -b puppy origin/puppy
        python3 qemu_runner.py --system $TEST_QEMU_ARCH --machine $TEST_QEMU_MACHINE --elf ../puppy.bin --extend='-bios none -smp 4'
        cat rtt_console.log
        popd
